# Generated by Django 5.0.4 on 2024-05-05 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0003_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_hod', to='admin_area.hod'),
        ),
        migrations.AddField(
            model_name='department',
            name='num_terminals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='num_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='terminal_heads',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='unit_heads',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_department', to='admin_area.department'),
        ),
    ]
