# Generated by Django 5.0.4 on 2024-05-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hod', '0005_unit_unit_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('fault', models.TextField()),
                ('rectification', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.terminal')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.user')),
            ],
        ),
    ]
